# *Numpy*

core library of python for Numerical Analysis in Python.
How to use?
start your code with import numpy as np.
Numpy is simillar to lists except that numpy is much much faster than lists.

### 1-D Array

In [4]:
import numpy as np
a = np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [5]:
type(a)

numpy.ndarray

### 2-D Array

In [11]:
import numpy as np
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
type(b)

numpy.ndarray

In [21]:
import numpy as np

c = np.array([[2,2,2],[3,3,3]])
c

array([[2, 2, 2],
       [3, 3, 3]])

In [16]:
d = np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [17]:
e = np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [18]:
f = np.empty(5)
f

array([1., 1., 1., 1., 1.])

In [23]:
g = np.arange(6)
g

array([0, 1, 2, 3, 4, 5])

In [24]:
h = np.arange(2,20)
h

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
i = np.arange(2,20,2)
i

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# An array from 2 to 20 that is spaced linearly by 5.
j = np.linspace(2,20,num=5)
j

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [29]:
# Create a specific data type array
k = np.ones(5,dtype=np.int8)
k

array([1, 1, 1, 1, 1], dtype=int8)

In [30]:
l = np.ones(5,dtype=np.float64)
l

array([1., 1., 1., 1., 1.])

In [33]:
m = np.zeros((3,4),dtype=np.int8)
m

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [34]:
n = np.ones((6,8),dtype=np.float64)
n

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

1-D array is actually called a vector.
A matrix refers to a 2-D array.

### 3-D Array

For 3-D or higher dimensional array, the term Tensor is also used. TensorFlow is a free and open source software for machine learning and artificial intelligence.

In [36]:
o = np.arange(24).reshape(2,3,4)
o

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])